### ISSUE TITLE
关于私密文件

### ISSUE THREAD

**Issue by woshilinqin** [shanyuhai123/documents#1]
UP主，私密文件放到 secreKeyConf.js 最终还是上传了github中，如何可以 git忽略掉。travis-ci 又可以自动化部署呢？

**Comment by shanyuhai123** [comment]
1. git 没有忽略的话应该是你之前将其添加到已跟踪（tracked），取消即可。[解决链接](https://docs.shanyuhai.top/tools/git/gitignore.html#%E8%A7%84%E5%88%99%E4%B8%8D%E7%94%9F%E6%95%88)；
2. travis-ci 你看一下对应视频（或自己执行），执行时存在 export 环境变量的步骤，可以使用 [config](https://www.npmjs.com/package/config) 来获取变量，详情查看他的 API 就好了。

**Comment by woshilinqin** [comment]
> 1. git 没有忽略的话应该是你之前将其添加到已跟踪（tracked），取消即可。[解决链接](https://docs.shanyuhai.top/tools/git/gitignore.html#%E8%A7%84%E5%88%99%E4%B8%8D%E7%94%9F%E6%95%88)；
> 2. travis-ci 你看一下对应视频（或自己执行），执行时存在 export 环境变量的步骤，可以使用 [config](https://www.npmjs.com/package/config) 来获取变量，详情查看他的 API 就好了。

这个应该可以解决我的问题。
