### ISSUE TITLE
关于运行deploy编译时的报错？

### ISSUE THREAD

**Issue by demigodliu** [shanyuhai123/documents#2]
![image](https://user-images.githubusercontent.com/30372735/64070942-e6c4c680-cca0-11e9-8ba2-cedfe29a7467.png)
![image](https://user-images.githubusercontent.com/30372735/64070943-f04e2e80-cca0-11e9-8a39-7a0dcdad33ea.png)

运行时dist文件目录已经生成了，但是最后却报了个这个错，请大佬帮忙看看，十分感谢！！

**Comment by demigodliu** [comment]
项目地址：https://github.com/demigodliu/blog-vp

**Comment by demigodliu** [comment]
问题已解决：https://blog.csdn.net/weixin_44394753/article/details/91410463

**Comment by shanyuhai123** [comment]
> 问题已解决：https://blog.csdn.net/weixin_44394753/article/details/91410463

一般来说是先提供 ssh key，然后就可以利用 git 协议拷贝下来，你可能是用 https 协议拷贝下来的，所以会陷入这个问题。还是说你是先新建了本地项目，最后 git remote add 到远程了。
