### ISSUE TITLE
插件

### ISSUE THREAD

**Issue by Lucasie** [shanyuhai123/documents#21]
![image](https://user-images.githubusercontent.com/4027656/147222807-cec5d44d-0b3c-4a2b-b0f1-50df105e90f2.png)
这个是什么插件实现的mac os 风格

**Comment by shanyuhai123** [comment]
不是插件，自己补了点样式，[代码](https://github.com/shanyuhai123/documents/blob/master/docs/.vuepress/styles/index.scss#L10)
