### ISSUE TITLE
PWA图标不显示

### ISSUE THREAD

**Issue by txu1** [shanyuhai123/documents#6]
博客地址是 https://txu1.gitee.io/blog/

可以离线安装PWA，各种尺寸的图标也加载到了，Vuepress也是最新版，也设置了apple-touch-icon

可为什么移动端Safari添加到主屏幕时，APP图标是默认状态下的网页截图而不是给定的图标？？？

**Comment by shanyuhai123** [comment]
抱歉我仅有安卓，Safari 上没有测试过。
